name: 'tag-exists-action'
description: 'Checks if a given tag exists'
inputs:
  tag:  
    description: 'Tag to search for'
    required: true
outputs:
  exists: # id of output
    description: 'true or false'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'bookmark'  
  color: 'yellow'
